name: Release to Maven Central
on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: central
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}

      - name: List keys
        run: gpg -K

      - name: Set version
        run: mvn versions:set -DnewVersion=${{ env.RELEASE_VERSION }}

      - name: Publish package
        run: ./mvnw --batch-mode deploy -DskipTests