name: Release to Maven Central

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Decrypt GPG key
        env:
          SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          SIGNING_KEY_PASSWORD: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
        run: |
          echo "$SIGNING_KEY" | base64 --decode | gpg --import --batch --yes --passphrase "$SIGNING_KEY_PASSWORD"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Publish to Maven Central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.GPG_SIGNING_KEY_ID }}
          SIGNING_KEY_PASSWORD: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
          GITHUB_RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
        run: ./gradlew publish